apiVersion: v1
kind: Template
metadata:
  name: opensuse15
  annotations:
    openshift.io/display-name: "OpenSUSE Leap 15.0 VM"
    description: >-
      This template can be used to create a VM suitable for
      OpenSUSE Leap 15.0.
      The template assumes that a PVC is available which is providing the
      necessary OpenSUSE disk image.

      Recommended disk image (needs to be converted to raw)
      https://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.0/images/
    tags: "kubevirt,virtualmachine,linux,opensuse"
    iconClass: "icon-fedora"
    openshift.io/provider-display-name: "KubeVirt"
    openshift.io/documentation-url: "https://github.com/fabiand/common-templates"
    openshift.io/support-url: "https://github.com/fabiand/common-templates/issues"
    template.openshift.io/bindable: "false"

    defaults.template.cnv.io/disk: rootdisk
    template.cnv.io/editable: |
      /objects[0].spec.template.spec.domain.cpu.cores
      /objects[0].spec.template.spec.domain.resources.requests.memory
      /objects[0].spec.template.spec.domain.devices.disks
      /objects[0].spec.template.spec.volumes
      /objects[0].spec.template.spec.networks

  labels:
    os.template.cnv.io/opensuse15.0: "true"
    workload.template.cnv.io/server: "true"
    workload.template.cnv.io/desktop: "true"
    flavor.template.cnv.io/small: "true"

objects:
- apiVersion: kubevirt.io/v1alpha2
  kind: VirtualMachine
  metadata:
    name: ${NAME}
  spec:
    running: false
    template:
      spec:
        domain:
          cpu:
            cores: 2
          resources:
            requests:
              memory: 2G
          devices:
            rng: {}
            disks:
            - disk:
                bus: virtio
              name: rootdisk
              volumeName: rootvolume
        terminationGracePeriodSeconds: 0
        volumes:
        - name: rootvolume
          persistentVolumeClaim:
            claimName: ${PVCNAME}
        - cloudInitNoCloud:
            userData: |-
              # configure default password
              password: fedora
              chpasswd: { expire: False }
          name: cloudinitvolume

parameters:
- description: VM name
  from: '[a-z0-9]{16}'
  generate: expression
  name: NAME
- name: PVCNAME
  description: Name of the PVC with the disk image
  required: true

