apiVersion: v1
kind: Template
metadata:
  name: ubuntu1604
  annotations:
    openshift.io/display-name: "Ubuntu 16.04 (Xenial Xerus) VM"
    description: >-
      This template can be used to create a VM suitable for
      Ubuntu 16.04 (Xenial Xerus).
      The template assumes that a PVC is available which is providing the
      necessary Ubuntu disk image.

      Recommended disk image (needs to be converted to raw)
      http://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img
    tags: "kubevirt,virtualmachine,ubuntu"
    iconClass: "icon-ubuntu"
    openshift.io/provider-display-name: "KubeVirt"
    openshift.io/documentation-url: "https://github.com/fabiand/common-templates"
    openshift.io/support-url: "https://github.com/fabiand/common-templates/issues"
    template.openshift.io/bindable: "false"
  labels:
    kubevirt.io/os: ubuntu1604
objects:
- apiVersion: kubevirt.io/v1alpha2
  kind: VirtualMachineInstancePreset
  metadata:
    name: ubuntu1604
  spec:
    selector:
      matchLabels:
        kubevirt.io/os: ubuntu1604
    domain:
      cpu:
        model: Conroe
        cores: 2
      devices: {}
      resources:
        requests:
          memory: 2G
- apiVersion: kubevirt.io/v1alpha2
  kind: VirtualMachine
  metadata:
    labels:
      kubevirt.io/os: ubuntu1604
    name: ${NAME}
  spec:
    running: false
    template:
      metadata:
        labels:
          kubevirt.io/os: ubuntu1604
      spec:
        domain:
          devices:
            disks:
            - disk:
                bus: virtio
              name: rootdisk
              volumeName: rootvolume
        terminationGracePeriodSeconds: 0
        volumes:
        - name: rootvolume
          persistentVolumeClaim:
            claimName: ${PVCNAME}
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: ubuntu
              chpasswd: { expire: False }
          name: cloudinitvolume
parameters:
- name: NAME
  description: Name of the new VM
  generate: expression
  from: "ubuntu1604-[a-z0-9]{6}"
  required: true
- name: PVCNAME
  description: Name of the PVC with the disk image
  required: true
