apiVersion: v1
kind: Template
metadata:
  name: win2k12r2
  annotations:
    openshift.io/display-name: "Microsoft Windows Server 2012 R2 VM"
    description: >-
      This template can be used to create a VM suitable for
      Microsoft Windows Server 2012 R2.
      The template assumes that a PVC is available which is providing the
      necessary Windows disk image.
    tags: "kubevirt,virtualmachine,windows"
    iconClass: "icon-windows"
    openshift.io/provider-display-name: "KubeVirt"
    openshift.io/documentation-url: "https://github.com/fabiand/common-templates"
    openshift.io/support-url: "https://github.com/fabiand/common-templates/issues"
    template.openshift.io/bindable: "false"

    defaults.template.cnv.io/disk: rootdisk
    defaults.template.cnv.io/network: default
    template.cnv.io/editable:
    - "/objects[0].spec.template.spec.domain.cpu.cores"
    - "/objects[0].spec.template.spec.domain.resources.requests.memory"
    - "/objects[0].spec.template.spec.domain.devices.disks"
    - "/objects[0].spec.template.spec.volumes"
    - "/objects[0].spec.template.spec.networks"

  labels:
    os.template.cnv.io/win2k12r2: true
    os.template.cnv.io/win2k8r2: true
    os.template.cnv.io/win2k8: true
    os.template.cnv.io/win10: true
    workload.template.cnv.io/server: true
    workload.template.cnv.io/desktop: true
    flavor.template.cnv.io/medium: true
objects:
- apiVersion: kubevirt.io/v1alpha2
  kind: VirtualMachine
  metadata:
    labels:
      kubevirt.io/os: win2k12r2
    name: ${NAME}
  spec:
    running: false
    template:
      spec:
        domain:
          clock:
            utc: {}
            timer:
              hpet:
                present: false
              pit:
                tickPolicy: delay
              rtc:
                tickPolicy: catchup
              hyperv: {}
          cpu:
            cores: 2
          resources:
            requests:
              memory: 4G
          features:
            acpi: {}
            apic: {}
            hyperv:
              relaxed: {}
              vapic: {}
              spinlocks:
                spinlocks: 8191
          devices:
            disks:
            - disk:
                bus: sata
              name: rootdisk
              volumeName: rootvolume
            interfaces:
            - bridge: {}
              model: e1000e
              name: default
        terminationGracePeriodSeconds: 0
        volumes:
        - name: rootvolume
          persistentVolumeClaim:
            claimName: ${PVCNAME}
        networks:
        - name: default
          pod: {}

parameters:
- description: Name of the new VM
  from: '[A-Za-z0-9]{1,16}'
  generate: expression
  name: NAME
- name: PVCNAME
  description: Name of the PVC with the disk image
  required: true
